# ======================
# THEME CONFIGURATION
# ======================
[theme]
# Primary accent color for interactive elements
primaryColor = "#000000"

# Main background color
backgroundColor = "#0e1117"

# Background color for sidebar and widgets
secondaryBackgroundColor = "#1a1a1a"

# Default text color
textColor = "#fafafa"

# Application font family
font = "sans serif"

# ======================
# SERVER SETTINGS
# ======================
[server]
# Maximum file upload size in MB
maxUploadSize = 200

# Cross-Origin Resource Sharing
enableCORS = false

# Security protection against CSRF attacks
enableXsrfProtection = true

# ======================
# BROWSER SETTINGS
# ======================
[browser]
# Disable Streamlit usage statistics
gatherUsageStats = false

# ======================
# LOGGING CONFIGURATION
# ======================
[logger]
# Console log level (debug, info, warning, error, critical)
level = "info"

# ======================
# UI SETTINGS
# ======================
[client]
# Hide the default Streamlit toolbar
toolbarVisible = false

# Hide the default sidebar navigation
showSidebarNavigation = false